name: Java Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build the file
        run: gradle build
        
      - run: ls ./build/libs

      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          path: ./build/libs/
          retention-days: 5
        


