name: Java Workflow

on:
  push:
    branches:
      - main

jobs:


  component-analysis:
    runs-on: ubuntu-latest
    needs: testing
    steps:

      - uses: actions/checkout@v2

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - run: gradlew pmdMain pmdTest

      - uses: actions/upload-artifact@v2
        with:
          name: PMDScanOutput
          path: build/reports/pmd