name: Java Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build the file
        run: gradle build
        
      - run: ls ./build/libs

      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          path: ./build/libs/
          retention-days: 5

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Jar file in the Background and test
        run: |
          java -jar ./build/libs/cars-api.jar &
          sleep 30
          curl http://localhost:5000/cars/1 | grep -i "Ford"
          




